"use client";

import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { ago, apiGet, apiPost, label } from "@/lib/api";
import type { Alert, Hotspot } from "@/lib/types";
import { ConfidenceBreakdown, FreshnessList, StatusBadge } from "@/components/panels";

type Props = { alert: Alert; officer: string; onChanged: () => void };

export function AlertDetail({ alert, officer, onChanged }: Props) {
  const [hotspot, setHotspot] = useState<Hotspot | null>(null);
  const [approved, setApproved] = useState<string[]>(
    () => alert.action_brief.recommended_actions.filter((a) => a.priority === "high").map((a) => a.action_id),
  );
  const [actionText, setActionText] = useState("");
  const [resolution, setResolution] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const brief = alert.action_brief;
  const prov = alert.brief_provenance;

  useEffect(() => {
    let live = true;
    apiGet<Hotspot>(`/api/hotspots/${alert.hotspot_id}`)
      .then((h) => live && setHotspot(h))
      .catch(() => live && setHotspot(null));
    return () => {
      live = false;
    };
  }, [alert.hotspot_id, alert.status]);

  async function run(path: string, body: object) {
    setBusy(true);
    setError(null);
    try {
      await apiPost(`/api/alerts/${alert.alert_id}/${path}`, { officer, ...body });
      onChanged();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }

  const sug = alert.cross_boundary_suggestion;
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex flex-wrap items-center gap-2">
          <span className="font-mono">{alert.alert_id}</span>
          <StatusBadge status={alert.status} />
          <Badge variant="outline">risk: {brief.risk_level}</Badge>
          {alert.kind === "cross_boundary" && (
            <Badge className="bg-purple-600 text-white">Cross-boundary from {alert.origin_jurisdiction_id}</Badge>
          )}
        </CardTitle>
        <CardDescription>
          {alert.jurisdiction_name} · sent {ago(alert.sent_at)} · hotspot {alert.hotspot_id}
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-4 lg:grid-cols-2">
        <div className="space-y-3">
          <section>
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">AI action brief (draft for your review)</h3>
            <p className="mt-1">{brief.summary}</p>
            <p className="mt-1 text-[11px] text-muted-foreground">
              {prov.mode === "gemini" ? "Generated by" : "Demo mode:"} {prov.model_name} ({prov.model_version}) · prompt{" "}
              {prov.prompt_version}
              {prov.note ? ` · ${prov.note}` : ""}
            </p>
            {!!prov.validation_warnings?.length && (
              <p className="mt-1 text-xs text-red-600">Validation: {prov.validation_warnings.join("; ")}</p>
            )}
          </section>
          <section>
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">Likely sources (to guide inspection)</h3>
            <ul className="mt-1 space-y-1">
              {brief.likely_sources.map((s) => (
                <li key={s.type} className="flex items-center gap-2">
                  <div className="h-2 rounded bg-orange-500" style={{ width: `${Math.max(4, s.confidence * 120)}px` }} />
                  <span className="capitalize">Likely {label(s.type)}</span>
                  <span className="text-xs text-muted-foreground">{s.confidence.toFixed(2)}</span>
                </li>
              ))}
            </ul>
          </section>
          <section>
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">Evidence (observed data)</h3>
            <ul className="mt-1 space-y-1 text-xs">
              {brief.evidence.map((e, i) => (
                <li key={i}>
                  • <b>{e.signal}</b>: {e.value}
                  <span className="block pl-3 text-[11px] text-muted-foreground">
                    {e.source} · {ago(e.observed)}
                  </span>
                </li>
              ))}
            </ul>
          </section>
          <section>
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">Forecast outlook</h3>
            <p className="text-xs">{brief.forecast_outlook}</p>
          </section>
          <section>
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">Uncertainties</h3>
            <ul className="list-disc pl-5 text-xs">
              {brief.uncertainties.map((u) => (
                <li key={u}>{u}</li>
              ))}
            </ul>
          </section>
        </div>

        <div className="space-y-4">
          {hotspot && (
            <section>
              <h3 className="mb-1 text-xs font-semibold uppercase text-muted-foreground">
                Hotspot Confidence · {hotspot.h3_cells.length} cell(s){hotspot.fast_path ? " · fast path" : ""}
              </h3>
              <ConfidenceBreakdown
                confidence={hotspot.confidence}
                band={hotspot.band}
                factors={hotspot.factors}
                threshold={hotspot.threshold}
              />
            </section>
          )}

          <section className="space-y-2 rounded-lg border p-3">
            <h3 className="text-xs font-semibold uppercase text-muted-foreground">Recommended inspection (approve to record)</h3>
            {brief.recommended_actions.map((a) => (
              <label key={a.action_id} className="flex items-start gap-2 text-xs">
                <input
                  type="checkbox"
                  className="mt-0.5"
                  disabled={alert.status !== "pending_review"}
                  checked={
                    alert.status === "pending_review"
                      ? approved.includes(a.action_id)
                      : alert.approved_action_ids.includes(a.action_id)
                  }
                  onChange={(ev) =>
                    setApproved((cur) => (ev.target.checked ? [...cur, a.action_id] : cur.filter((x) => x !== a.action_id)))
                  }
                />
                <span>
                  <Badge variant="outline" className="mr-1">
                    {a.priority}
                  </Badge>
                  {a.action} <span className="font-mono text-[10px] text-muted-foreground">{a.action_id}</span>
                </span>
              </label>
            ))}
            {alert.status === "pending_review" && (
              <Button disabled={busy} onClick={() => run("acknowledge", { approved_action_ids: approved })}>
                Acknowledge &amp; approve selected actions
              </Button>
            )}
            {(alert.status === "acknowledged" || alert.status === "action_taken") && (
              <div className="flex gap-2">
                <Input
                  placeholder="Action taken (e.g. inspection team dispatched)"
                  value={actionText}
                  onChange={(e) => setActionText(e.target.value)}
                />
                <Button disabled={busy || !actionText} onClick={() => run("action", { action_taken: actionText })}>
                  Record action
                </Button>
              </div>
            )}
            {(alert.status === "acknowledged" || alert.status === "action_taken") && (
              <div className="flex gap-2">
                <Input placeholder="Resolution" value={resolution} onChange={(e) => setResolution(e.target.value)} />
                <Button variant="outline" disabled={busy || !resolution} onClick={() => run("close", { resolution })}>
                  Close alert
                </Button>
              </div>
            )}
            {alert.action_taken && <p className="text-xs">Action recorded: {alert.action_taken}</p>}
            {alert.resolution && <p className="text-xs">Resolution: {alert.resolution}</p>}
          </section>

          {sug && (
            <section className="space-y-2 rounded-lg border border-purple-400 p-3">
              <h3 className="text-xs font-semibold uppercase text-purple-700">Cross-boundary impact likely</h3>
              <p className="text-xs">
                {sug.reason}. {sug.target_name} is ~{sug.distance_km} km downwind; smoke may arrive in ~{sug.eta_hours} h.
              </p>
              {alert.cross_boundary_alert_id ? (
                <p className="text-xs">
                  Sent to {sug.target_jurisdiction_id} as <span className="font-mono">{alert.cross_boundary_alert_id}</span>
                </p>
              ) : (
                <Button
                  disabled={busy || alert.status === "pending_review"}
                  onClick={() => run("cross-boundary", { note: "Approved from officer dashboard" })}
                >
                  Send cross-boundary alert to {sug.target_name}
                </Button>
              )}
              {alert.status === "pending_review" && !alert.cross_boundary_alert_id && (
                <p className="text-[11px] text-muted-foreground">Acknowledge the alert first (human approval).</p>
              )}
            </section>
          )}

          {error && <p className="text-xs text-red-600">{error}</p>}

          {hotspot?.evidence_bundle && (
            <section>
              <h3 className="mb-1 text-xs font-semibold uppercase text-muted-foreground">Data freshness</h3>
              <FreshnessList items={hotspot.evidence_bundle.data_freshness} />
            </section>
          )}

          <section>
            <h3 className="mb-1 text-xs font-semibold uppercase text-muted-foreground">Audit trail</h3>
            <ul className="space-y-0.5 text-[11px]">
              {alert.history.map((h, i) => (
                <li key={i}>
                  {ago(h.at)} · <b>{h.actor}</b> · {label(h.event)} {h.note && `: ${h.note}`}
                </li>
              ))}
            </ul>
          </section>
        </div>
      </CardContent>
    </Card>
  );
}
